[versions]
gradle-plugin = "7.2.1"
kotlin = "1.6.21"
lifecycle = "2.5.1"
core_ktx = "1.8.0"
appcompat = "1.4.2"
material = "1.6.1"
constraintlayout = "2.1.4"
maps_version = "18.1.0"
retrofit = "2.9.0"
junit = "4.13.2"
junit-android = "1.1.3"
junit-android-core = "3.4.0"
google-maps = "18.1.0"
activity-ktx = "1.5.1"

[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }

activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activity-ktx" }
viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }

retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }

junit = { module = "junit:junit", version.ref = "junit" }
junit-android = { module = "androidx.test.ext:junit", version.ref = "junit-android" }
junit-android-core = { module = "androidx.test.espresso:espresso-core", version.ref = "junit-android-core" }
google-maps = { module = "com.google.android.gms:play-services-maps", version.ref = "google-maps" }

[plugins]
android-application = { id = "com.android.application", version.ref = "gradle-plugin" }
android-library = { id = "com.android.library", version.ref = "gradle-plugin" }
android-kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

[bundles]
android-core = ["androidx-core-ktx", "appcompat", "material", "constraintlayout"]
lifecycle = ["viewmodel-ktx", "livedata-ktx", "runtime-ktx"]
retrofit = ["retrofit", "retrofit-converter"]
junit-android = ["junit-android", "junit-android-core"]